# SPDX-FileCopyrightText: 2021 Eric Neidhardt
# SPDX-License-Identifier: CC0-1.0

name: Static Analysis
on: [push, pull_request]

jobs:

  build:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install golang.org/x/lint/golint@latest

    - name: staticcheck
      run: staticcheck ./...
